### ISSUE TITLE
binary file

### ISSUE THREAD

**Issue by hawkhsieh** [imagora/FlvParser#2]
Hope the executable is exist in the github so that we could execute it directly without compile...

**Comment by winking324** [comment]
you can download it from:
https://pan.baidu.com/s/1tPhQB3c0moK39qypcAuNTg 
with code: qgpw

this binary is for mac

**Comment by winking324** [comment]
> Hope the executable is exist in the github so that we could execute it directly without compile...

you can download it from:
`https://pan.baidu.com/s/1tPhQB3c0moK39qypcAuNTg`
with code: `qgpw`

this binary is for mac
